### ISSUE TITLE
Master Detail view issue

### ISSUE THREAD

**Issue by masouddehghani** [wilsonvargas/ButtonCirclePlugin#17]
After adding this plugin to my project, setting Detail to a page on my MainPage raises "Object reference not set to an instance of an object" exception:

this.Detail = new NavigationPage(page);

I've checked and can confirm that Detail and page are both initiated.

The stacktrace of the exception can be found below:
   
ButtonCircle.FormsPlugin.UWP.ButtonCircleRenderer.OnElementChanged(ElementChangedEventArgs`1 e)
   at Xamarin.Forms.Platform.UWP.VisualElementRenderer`2.SetElement(VisualElement element)
   at Xamarin.Forms.Platform.UWP.VisualElementRenderer`2.Dispose(Boolean disposing)
   at Xamarin.Forms.Platform.UWP.VisualElementRenderer`2.Dispose()
   at Xamarin.Forms.Platform.UWP.VisualElementExtensions.Cleanup(VisualElement self)
   at Xamarin.Forms.Platform.UWP.NavigationPageRenderer.SetPage(Page page, Boolean isAnimated, Boolean isPopping)
   at Xamarin.Forms.Platform.UWP.NavigationPageRenderer.Dispose(Boolean disposing)
   at Xamarin.Forms.Platform.UWP.NavigationPageRenderer.Dispose()
   at Xamarin.Forms.Platform.UWP.MasterDetailPageRenderer.ClearDetail()
   at Xamarin.Forms.Platform.UWP.MasterDetailPageRenderer.UpdateDetail()
   at Xamarin.Forms.Platform.UWP.MasterDetailPageRenderer.OnElementPropertyChanged(Object sender, PropertyChangedEventArgs e)
   at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   at Xamarin.Forms.BindableObject.OnPropertyChanged(String propertyName)
   at Xamarin.Forms.Element.OnPropertyChanged(String propertyName)
   at Xamarin.Forms.MasterDetailPage.set_Detail(Page value)
   at MyTestProject.Views.MainPage.ListView_ItemSelected(Object sender, SelectedItemChangedEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Xamarin.Forms.ListView.OnSelectedItemChanged(BindableObject bindable, Object oldValue, Object newValue)
   at Xamarin.Forms.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent)
   at Xamarin.Forms.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes)
   at Xamarin.Forms.ListView.NotifyRowTapped(Int32 groupIndex, Int32 inGroupIndex, Cell cell)
   at Xamarin.Forms.ListView.NotifyRowTapped(Int32 index, Cell cell)
   at Xamarin.Forms.Platform.UWP.ListViewRenderer.OnListItemClicked(Object sender, ItemClickEventArgs e)

Any help would be highly appreciated.

Thanks.

**Comment by wilsonvargas** [comment]
In your UWP project add materialicons.ttf and fontawesome.ttf files to:

Assets/Fonts

You can download this file here:

[Material Design icons](https://github.com/wilsonvargas/ButtonCirclePlugin/blob/master/src/ButtonCircle/ButtonCircle.FormsPlugin.UWP/Assets/Fonts/materialicons.ttf)

[FontAwesome](https://github.com/wilsonvargas/ButtonCirclePlugin/blob/master/src/ButtonCircle/ButtonCircle.FormsPlugin.UWP/Assets/Fonts/fontawesome.ttf)

It's ok?

**Comment by helzgate** [comment]
I get the exact same error.  It works fine when the home page loads (that is a master detail page), but as soon as I navigate to another page, that's when the error pops up.  Judging by the error, it looks like there is an issue destroying the CicrcleButton.  

I'm not using PCL, i'm using .Net Standard 2.0 for my shared Library

Issue occurs using Xamarin.Forms in a UWP app where both Both Target and Min versions are 10.0;Build 16299
    "Autofac": "4.6.2",
    "Microsoft.NETCore.UniversalWindowsPlatform": "6.0.2",
    "Newtonsoft.Json": "10.0.3",
    "Plugins.Forms.ButtonCircle": "2.0.1-beta",
    "ReactiveUI": "8.0.0-alpha0117",
    "ReactiveUI.Events.XamForms": "8.0.0-alpha0117",
    "ReactiveUI.XamForms": "8.0.0-alpha0117",
    "SkiaSharp": "1.59.1",
    "Splat": "2.0.0",
    "Xamarin.FFImageLoading.Svg.Forms": "2.2.25",
    "Xamarin.FFImageLoading.Transformations": "2.2.25",
    "Xamarin.Forms": "2.5.0.121934"
